### ISSUE TITLE
Problem to create flatten intraday tables

### ISSUE THREAD

**Issue by pierrehabte2017** [adswerve/google_analytics_flattener_ga4#2]
I have this error that appears in  ga-flattener-deployment-cfintraday cloud function logs when trying to create flatten tables for intradays tables:

`2022-02-09 06:59:53.568 PSTga-flattener-deployment-cfintradayex4immrg5l14 Exception on /_ah/push-handlers/pubsub/projects/[my_project]/topics/ga-flattener-deployment-topic-intraday [POST] Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app response = self.full_dispatch_request() File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request rv = self.dispatch_request() File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File "/layers/google.python.pip/pip/lib/python3.7/site-packages/functions_framework/__init__.py", line 171, in view_func function(data, context) File "/workspace/main.py", line 159, in manage_intraday_schedule input_event = InputValidatorIntraday(event) File "/workspace/main.py", line 16, in __init__ self.method_name = message_payload['protoPayload']["methodName"] KeyError: 'methodName'

Exception on /_ah/push-handlers/pubsub/projects/[my_project]/topics/ga-flattener-deployment-topic-intraday [POST] Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app response = self.full_dispatch_request() File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request rv = self.dispatch_request() File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File "/layers/google.python.pip/pip/lib/python3.7/site-packages/functions_framework/__init__.py", line 171, in view_func function(data, context) File "/workspace/main.py", line 159, in manage_intraday_schedule input_event = InputValidatorIntraday(event) File "/workspace/main.py", line 16, in __init__ self.method_name = message_payload['protoPayload']["methodName"] KeyError: 'methodName'
`

Any tips ?

**Comment by RuslanBergenov** [comment]
Hi @pierrehabte2017, thank you for submitting the issue, we'll investigate and get back to you.

**Comment by RuslanBergenov** [comment]
@pierrehabte2017, I'll close this issue due to inactivity, but if you need further assistance, please provide the details above. Have a great weekend!
