### ISSUE TITLE
event_id null in flat_events and flat_event_params

### ISSUE THREAD

**Issue by robertlmyers** [adswerve/google_analytics_flattener_ga4#22]
Hi Ruslan, Per our discussion, there are event_id fields coming in from flat_events as well as flat_event_params.  It looks to be about 1% of the records per day.
Thanks,
Rob

**Comment by RuslanBergenov** [comment]
Thank you Robert, I will look into it and will give you an update.

**Comment by RuslanBergenov** [comment]
@robertlmyers , I am unable to replicate the issue.

I used the following query:

```
SELECT DISTINCT event_id FROM `{project}.analytics_{ga4_property}.flat_events_*`
ORDER BY 1 NULLS FIRST
 LIMIT 1000
```

Are any of the following fields NULL in your source GA4 data?
  "stream_id",
  "user_pseudo_id",
  "event_name",
  "event_timestamp"

**Comment by RuslanBergenov** [comment]
@robertlmyers, 
This issue has been solved in this release:
https://github.com/adswerve/google_analytics_flattener_ga4/releases/tag/v1.3.0
