### ISSUE TITLE
How to Test?

### ISSUE THREAD

**Issue by efrazier** [adswerve/google_analytics_flattener_ga4#9]
It wasn't super clear to me at first that this is intended to run as a job, I get that now from the config section. But what I can't figure out is how exactly to test this by hand. When I try, I get an error from cf/main.py about the event['data'] being undef.

" line 19, in __init__ message_payload = json.loads(base64.b64decode(event['data']).decode('utf-8')) KeyError: 'data'"

19: message_payload = json.loads(base64.b64decode(event['data']).decode('utf-8'))

And it looks like this is because of some event triggering this method, like a new day table being written? 

Also, from what I understand, I should run the cfconfigbuilder when I update my config_datasets.json. I got a 200 at least when I did that, but I wasn't sure either if this was required or not.  If I don't have a frequency set in the config file, I would think this won't run at all.. 

Thanks!

**Comment by efrazier** [comment]
It looks like the best way to test is to run the backfill from tools/pubsub_message_publish.py It still isn't clear to me how the config works because I haven't been able to update my config in spite of double checking the yaml buckets and running the configbuilder. I still get errors saying intraday isn't enabled and the config is still the default.

**Comment by RuslanBergenov** [comment]
@efrazier , apologies for the delay. 

RE: how to test: 
1) you're correct, running backfill from from tools/pubsub_message_publish.py does help verify that the flattener is working as expected. 
2) I also check the config file after installation to make sure it's been built correctly with its default options. This brings me to your next question. 

RE: how to edit the config file
- If you want non-default config file options, you need to do the following:
1) manually download the config file from GCS (Google Cloud Storage)
2) Edit it locally in a text/code upload
3) Upload the config file back to GCS and overwrite the old version.
We will make sure to add these steps to README. 

Does this help?

**Comment by RuslanBergenov** [comment]
RE:
Also, from what I understand, I should run the cfconfigbuilder when I update my config_datasets.json. 
- No, you don't need to run the cfconfigbuilder when you update your config_datasets.json. 

RE:
I got a 200 at least when I did that, but I wasn't sure either if this was required or not. If I don't have a frequency set in the config file, I would think this won't run at all.
- It's not required. 
- Correct, if you don't have frequency set in the config, then the intraday flattening won't run. Please see more details here: https://github.com/adswerve/google_analytics_flattener_ga4#examples-of-a-config-file

**Comment by RuslanBergenov** [comment]
We will close the issue for now, but we'll reopen if you have any further questions re: this matter.
